apiVersion: v1
kind: ConfigMap
metadata:
  name: server-configmap
data:
  server.toml: |
    # server.toml
    [server]
    bind_addr = "0.0.0.0:2333" # `2333` specifies the port that rathole listens for clients

    [server.services.my_proxy]
    token = "fd7a115ca1e02001753c" # Token that is used to authenticate the client for the service. Change to an arbitrary value.
    bind_addr = "0.0.0.0:8080" # `8080` specifies the port that exposes `my_proxy` to the Internet