appws:
  image:
    repository: nghia9691/npad-server
    tag: 0.0.3
  network:
    http:
      ingress:
        host: npad.baloise.dev
  env:
    - name: HOST
      value: "0.0.0.0"
    - name: YPERSISTENCE
      value: "/app/data/lvdb"
  persistence:
    name: data
    # storageClass:
    enabled: true
    accessModes: ReadWriteMany
    size: 5Gi
    volumeMountPath: /app/data 
