appws:
  image:
    repository: nghia9691/npad-server
    tag: 0.0.1
  network:
    http:
      ingress:
        host: npadws.baloise.dev
  # env:
    # - name: YPERSISTENCE
    #   value: "/app/data/lvdb"
  # persistence:
  #   name: data
  #   storageClass:
  #   enabled: true
  #   accessModes: ReadWriteMany
  #   size: 5Gi
  #   volumeMountPath: /app/data 
