apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: {{ .Release.Name }}
spec:
  endpoints:
    - dnsName: {{ .Values.app-ws.network.http.ingress.host }}
      recordType: A
      recordTTL: 180
      targets: [""]
