app:
  image:
    repository: nghia9691/fsync-server
    tag: 0.0.3
  network:
    http:
      ingress:
        host: fsync.baloise.dev
  env:
    - name: APP_STORAGE_PATH
      value: "/app/data"
    - name: SPRING_SERVLET_MULTIPART_MAXFILESIZE
      value: 10MB
  persistence:
    name: data
    enabled: true
    accessModes: ReadWriteMany
    size: 2Gi
    volumeMountPath: /app/data 
