app:
  image:
    repository: rapiz1/rathole
    tag: "v0.5.0"
  network:
    http: null
    control:
      servicePort: 2333
      containerPort: 2333
      ingress:
        host: rathole.baloise.dev
        insecureEdgeTerminationPolicy: Allow
    my-ssh:
      servicePort: 5202
      containerPort: 5202
      ingress:
        host: rathole.baloise.dev
        insecureEdgeTerminationPolicy: Allow
  volumeMounts:
    - name: mnt
      mountPath: /app/server.toml
      subPath: server.toml
  volumes:
    - name: mnt
      configMap:
        name: server-config-file
  args: ["/app/server.toml"]