app:
  image:
    repository: rapiz1/rathole
    tag: v0.5.0
  volumes:
    - name: server-config-vol
      configMap:
        name: server-configmap
  volumeMounts:
    - name: server-config-vol
      mountPath: /opt/config/server.toml
      subPath: server.toml
  command: ["/app/rathole", "--server", "/opt/config/server.toml"]