app:
  image:
    repository: nghia9691/bore
    tag: 0.5.0
  network:
    http: null
    tcp:
      servicePort: 7835
      containerPort: 7835
      ingress:
        host: bore.baloise.dev
        insecureEdgeTerminationPolicy: Allow
  env:
    - name: RUST_LOG
      value: Debug
  args: ["server"]
