app:
  image:
    repository: nghia9691/fsync-server
    tag: 0.0.1
  network:
    http:
      ingress:
        host: fsync.baloise.dev
  env:
    - name: APP_STORAGE_PATH
      value: "/app/data"
  persistence:
    name: data
    enabled: true
    accessModes: ReadWriteMany
    size: 3Gi
    volumeMountPath: /app/data 
